#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sebasTiendaMovil")]
	public partial class ConexionDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ConexionDBDataContext() : 
				base(global::Backend.Properties.Settings.Default.sebasTiendaMovilConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_CARRITO")]
		public int SP_INGRESAR_CARRITO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="Int")] System.Nullable<int> iDCLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDPRODUCTO", DbType="Int")] System.Nullable<int> iDPRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CANTIDAD", DbType="Int")] System.Nullable<int> cANTIDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE, iDPRODUCTO, cANTIDAD, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_CATEGORIA")]
		public int SP_INGRESAR_CATEGORIA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(MAX)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_DESCUENTO")]
		public int SP_INGRESAR_DESCUENTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCUENTO", DbType="Int")] System.Nullable<int> dESCUENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_INICIO", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_INICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_FIN", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_FIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dESCUENTO, fECHA_INICIO, fECHA_FIN, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_DOMICILIO")]
		public int SP_INGRESAR_DOMICILIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="Int")] System.Nullable<int> iDCLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="NVarChar(MAX)")] string dIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE, dIRECCION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_IMAGEN")]
		public int SP_INGRESAR_IMAGEN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDPRODUCTO", DbType="NVarChar(MAX)")] string iDPRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IMAGEN_NOMBRE", DbType="VarBinary(MAX)")] System.Data.Linq.Binary iMAGEN_NOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IMAGENURL", DbType="VarChar(MAX)")] string iMAGENURL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDPRODUCTO, iMAGEN_NOMBRE, iMAGENURL, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_PRODUCTO")]
		public int SP_INGRESAR_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO", DbType="NVarChar(9)")] string cODIGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(MAX)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(MAX)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STOCK", DbType="Int")] System.Nullable<int> sTOCK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRECIO", DbType="Decimal(10,0)")] System.Nullable<decimal> pRECIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PROVEEDOR", DbType="NVarChar(MAX)")] string nOMBRE_PROVEEDOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_CATEGORIA", DbType="NVarChar(MAX)")] string nOMBRE_CATEGORIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO, nOMBRE, dESCRIPCION, sTOCK, pRECIO, nOMBRE_PROVEEDOR, nOMBRE_CATEGORIA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(8)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_PROVEEDOR")]
		public int SP_INGRESAR_PROVEEDOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(MAX)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="NVarChar(MAX)")] string tELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, tELEFONO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_CATEGORIAS")]
		public ISingleResult<SP_OBTENER_CATEGORIASResult> SP_OBTENER_CATEGORIAS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_CATEGORIASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_DESCUENTOS")]
		public ISingleResult<SP_OBTENER_DESCUENTOSResult> SP_OBTENER_DESCUENTOS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_DESCUENTOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_DETALLES_PEDIDO")]
		public ISingleResult<SP_OBTENER_DETALLES_PEDIDOResult> SP_OBTENER_DETALLES_PEDIDO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_PEDIDO", DbType="NVarChar(9)")] string cODIGO_PEDIDO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO_PEDIDO);
			return ((ISingleResult<SP_OBTENER_DETALLES_PEDIDOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_DOMICILIO_CLIENTE")]
		public ISingleResult<SP_OBTENER_DOMICILIO_CLIENTEResult> SP_OBTENER_DOMICILIO_CLIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="Int")] System.Nullable<int> iDCLIENTE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE);
			return ((ISingleResult<SP_OBTENER_DOMICILIO_CLIENTEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PEDIDOS")]
		public ISingleResult<SP_OBTENER_PEDIDOSResult> SP_OBTENER_PEDIDOS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_PEDIDOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PRODUCTOS")]
		public ISingleResult<SP_OBTENER_PRODUCTOSResult> SP_OBTENER_PRODUCTOS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_PRODUCTOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PROVEEDORES")]
		public ISingleResult<SP_OBTENER_PROVEEDORESResult> SP_OBTENER_PROVEEDORES()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_PROVEEDORESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LOGIN")]
		public int SP_LOGIN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(MAX)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="NVarChar(MAX)")] string pASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="Int")] ref System.Nullable<int> iDCLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(MAX)")] ref string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="NVarChar(MAX)")] ref string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_USUARIO", DbType="Int")] ref System.Nullable<int> tIPO_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO_ELECTRONICO, pASSWORD, iDCLIENTE, nOMBRE, aPELLIDOS, tIPO_USUARIO, eRRORID, eRRORDESCRIPCION);
			iDCLIENTE = ((System.Nullable<int>)(result.GetParameterValue(2)));
			nOMBRE = ((string)(result.GetParameterValue(3)));
			aPELLIDOS = ((string)(result.GetParameterValue(4)));
			tIPO_USUARIO = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SELECCIONAR_PRODUCTOS")]
		public int SP_SELECCIONAR_PRODUCTOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO", DbType="NVarChar(9)")] string cODIGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDPRODUCTO_RETURN", DbType="Int")] ref System.Nullable<int> iDPRODUCTO_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_RETURN", DbType="NVarChar(9)")] ref string cODIGO_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PRODUCTO", DbType="NVarChar(MAX)")] ref string nOMBRE_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(MAX)")] ref string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STOCK", DbType="Int")] ref System.Nullable<int> sTOCK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRECIO", DbType="Decimal(18,0)")] ref System.Nullable<decimal> pRECIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PROVEEDOR", DbType="NVarChar(MAX)")] ref string nOMBRE_PROVEEDOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_CATEGORIA", DbType="NVarChar(MAX)")] ref string nOMBRE_CATEGORIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCUENTO", DbType="Int")] ref System.Nullable<int> dESCUENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO, iDPRODUCTO_RETURN, cODIGO_RETURN, nOMBRE_PRODUCTO, dESCRIPCION, sTOCK, pRECIO, nOMBRE_PROVEEDOR, nOMBRE_CATEGORIA, dESCUENTO, eRRORID, eRRORDESCRIPCION);
			iDPRODUCTO_RETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			cODIGO_RETURN = ((string)(result.GetParameterValue(2)));
			nOMBRE_PRODUCTO = ((string)(result.GetParameterValue(3)));
			dESCRIPCION = ((string)(result.GetParameterValue(4)));
			sTOCK = ((System.Nullable<int>)(result.GetParameterValue(5)));
			pRECIO = ((System.Nullable<decimal>)(result.GetParameterValue(6)));
			nOMBRE_PROVEEDOR = ((string)(result.GetParameterValue(7)));
			nOMBRE_CATEGORIA = ((string)(result.GetParameterValue(8)));
			dESCUENTO = ((System.Nullable<int>)(result.GetParameterValue(9)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(10)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(11)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_IMAGENES_PRODUCTO")]
		public ISingleResult<SP_OBTENER_IMAGENES_PRODUCTOResult> SP_OBTENER_IMAGENES_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDPRODUCTO", DbType="Int")] System.Nullable<int> iDPRODUCTO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDPRODUCTO);
			return ((ISingleResult<SP_OBTENER_IMAGENES_PRODUCTOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_PEDIDO")]
		public int SP_INGRESAR_PEDIDO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_PEDIDO", DbType="NVarChar(6)")] string cODIGO_PEDIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="Int")] System.Nullable<int> iDCLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOTAL", DbType="Decimal(10,0)")] System.Nullable<decimal> tOTAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="NVarChar(MAX)")] string dIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_PEDIDO_RETURN", DbType="NVarChar(6)")] string cODIGO_PEDIDO_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO_PEDIDO, iDCLIENTE, tOTAL, dIRECCION, iDRETURN, cODIGO_PEDIDO_RETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SELECCIONAR_PRODUCTO_CARRITOS")]
		public int SP_SELECCIONAR_PRODUCTO_CARRITOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDPRODUCTO", DbType="Int")] System.Nullable<int> iDPRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDPRODUCTO_RETURN", DbType="Int")] ref System.Nullable<int> iDPRODUCTO_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PRODUCTO", DbType="NVarChar(MAX)")] ref string nOMBRE_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STOCK", DbType="Int")] ref System.Nullable<int> sTOCK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRECIO", DbType="Decimal(18,0)")] ref System.Nullable<decimal> pRECIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCUENTO", DbType="Int")] ref System.Nullable<int> dESCUENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDPRODUCTO, iDPRODUCTO_RETURN, nOMBRE_PRODUCTO, sTOCK, pRECIO, dESCUENTO, eRRORID, eRRORDESCRIPCION);
			iDPRODUCTO_RETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			nOMBRE_PRODUCTO = ((string)(result.GetParameterValue(2)));
			sTOCK = ((System.Nullable<int>)(result.GetParameterValue(3)));
			pRECIO = ((System.Nullable<decimal>)(result.GetParameterValue(4)));
			dESCUENTO = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_CARRITOS")]
		public ISingleResult<SP_OBTENER_CARRITOSResult> SP_OBTENER_CARRITOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="Int")] System.Nullable<int> iDCLIENTE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE);
			return ((ISingleResult<SP_OBTENER_CARRITOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_CARRITO")]
		public int SP_ELIMINAR_CARRITO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCARRITO", DbType="Int")] System.Nullable<int> iDCARRITO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCARRITO_RETURN", DbType="Int")] ref System.Nullable<int> iDCARRITO_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCARRITO, iDCARRITO_RETURN, eRRORID, eRRORDESCRIPCION);
			iDCARRITO_RETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AGREGAR_CODIGO_CLIENTE")]
		public int SP_AGREGAR_CODIGO_CLIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="Int")] System.Nullable<int> iDCLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_VERIFICACION", DbType="NVarChar(6)")] string nUMERO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE_RETURN", DbType="Int")] ref System.Nullable<int> iDCLIENTE_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE, nUMERO_VERIFICACION, iDCLIENTE_RETURN, eRRORID, eRRORDESCRIPCION);
			iDCLIENTE_RETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PRODUCTOS_SEGUN_CATEGORIA")]
		public ISingleResult<SP_OBTENER_PRODUCTOS_SEGUN_CATEGORIAResult> SP_OBTENER_PRODUCTOS_SEGUN_CATEGORIA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCATEGORIA", DbType="Int")] System.Nullable<int> iDCATEGORIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCATEGORIA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_OBTENER_PRODUCTOS_SEGUN_CATEGORIAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PEDIDOS_CLIENTE")]
		public ISingleResult<SP_OBTENER_PEDIDOS_CLIENTEResult> SP_OBTENER_PEDIDOS_CLIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="Int")] System.Nullable<int> idCliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCliente);
			return ((ISingleResult<SP_OBTENER_PEDIDOS_CLIENTEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_DETALLE_PEDIDOS_CLIENTE")]
		public ISingleResult<SP_OBTENER_DETALLE_PEDIDOS_CLIENTEResult> SP_OBTENER_DETALLE_PEDIDOS_CLIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoPedido", DbType="NVarChar(6)")] string codigoPedido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoPedido);
			return ((ISingleResult<SP_OBTENER_DETALLE_PEDIDOS_CLIENTEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_CLIENTE")]
		public int SP_OBTENER_CLIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="Int")] System.Nullable<int> idCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_RETURN", DbType="NVarChar(MAX)")] ref string cORREO_RETURN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCliente, cORREO_RETURN);
			cORREO_RETURN = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_REGISTRARSE")]
		public int SP_REGISTRARSE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(MAX)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="NVarChar(MAX)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(MAX)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="NVarChar(MAX)")] string pASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_USUARIO", DbType="Int")] System.Nullable<int> tIPO_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="Int")] ref System.Nullable<int> iDCLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_RETURN", DbType="NVarChar(MAX)")] ref string nOMBRE_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS_RETURN", DbType="NVarChar(MAX)")] ref string aPELLIDOS_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_USUARIO_RETURN", DbType="Int")] ref System.Nullable<int> tIPO_USUARIO_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, aPELLIDOS, cORREO_ELECTRONICO, pASSWORD, tIPO_USUARIO, iDCLIENTE, nOMBRE_RETURN, aPELLIDOS_RETURN, tIPO_USUARIO_RETURN, eRRORID, eRRORDESCRIPCION);
			iDCLIENTE = ((System.Nullable<int>)(result.GetParameterValue(5)));
			nOMBRE_RETURN = ((string)(result.GetParameterValue(6)));
			aPELLIDOS_RETURN = ((string)(result.GetParameterValue(7)));
			tIPO_USUARIO_RETURN = ((System.Nullable<int>)(result.GetParameterValue(8)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(9)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class SP_OBTENER_CATEGORIASResult
	{
		
		private int _idCategoria;
		
		private string _NOMBRE;
		
		public SP_OBTENER_CATEGORIASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int NOT NULL")]
		public int idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					this._idCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_DESCUENTOSResult
	{
		
		private int _idDescuento;
		
		private System.DateTime _FECHA_INICIO;
		
		private System.DateTime _FECHA_FIN;
		
		public SP_OBTENER_DESCUENTOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDescuento", DbType="Int NOT NULL")]
		public int idDescuento
		{
			get
			{
				return this._idDescuento;
			}
			set
			{
				if ((this._idDescuento != value))
				{
					this._idDescuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_INICIO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_INICIO
		{
			get
			{
				return this._FECHA_INICIO;
			}
			set
			{
				if ((this._FECHA_INICIO != value))
				{
					this._FECHA_INICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_FIN", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_FIN
		{
			get
			{
				return this._FECHA_FIN;
			}
			set
			{
				if ((this._FECHA_FIN != value))
				{
					this._FECHA_FIN = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_DETALLES_PEDIDOResult
	{
		
		private int _CANTIDAD;
		
		private decimal _PRECIO;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		public SP_OBTENER_DETALLES_PEDIDOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD", DbType="Int NOT NULL")]
		public int CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this._CANTIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Decimal(10,0) NOT NULL")]
		public decimal PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_DOMICILIO_CLIENTEResult
	{
		
		private int _idDomicilio;
		
		private string _DIRECCION;
		
		public SP_OBTENER_DOMICILIO_CLIENTEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDomicilio", DbType="Int NOT NULL")]
		public int idDomicilio
		{
			get
			{
				return this._idDomicilio;
			}
			set
			{
				if ((this._idDomicilio != value))
				{
					this._idDomicilio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PEDIDOSResult
	{
		
		private int _idCliente;
		
		private string _CODIGO_PEDIDO;
		
		private int _ESTADO;
		
		private decimal _TOTAL;
		
		private string _DIRECCION;
		
		public SP_OBTENER_PEDIDOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", DbType="Int NOT NULL")]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					this._idCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_PEDIDO", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string CODIGO_PEDIDO
		{
			get
			{
				return this._CODIGO_PEDIDO;
			}
			set
			{
				if ((this._CODIGO_PEDIDO != value))
				{
					this._CODIGO_PEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Int NOT NULL")]
		public int ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Decimal(10,0) NOT NULL")]
		public decimal TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this._TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PRODUCTOSResult
	{
		
		private int _idProducto;
		
		private string _CODIGO;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private int _STOCK;
		
		private decimal _PRECIO;
		
		private string _NOMBRE_PROVEEDOR;
		
		private string _NOMBRE_CATEGORIA;
		
		private int _DESCUENTO;
		
		public SP_OBTENER_PRODUCTOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int NOT NULL")]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this._idProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="NVarChar(9) NOT NULL", CanBeNull=false)]
		public string CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this._CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCK", DbType="Int NOT NULL")]
		public int STOCK
		{
			get
			{
				return this._STOCK;
			}
			set
			{
				if ((this._STOCK != value))
				{
					this._STOCK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Decimal(10,0) NOT NULL")]
		public decimal PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PROVEEDOR", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NOMBRE_PROVEEDOR
		{
			get
			{
				return this._NOMBRE_PROVEEDOR;
			}
			set
			{
				if ((this._NOMBRE_PROVEEDOR != value))
				{
					this._NOMBRE_PROVEEDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_CATEGORIA", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NOMBRE_CATEGORIA
		{
			get
			{
				return this._NOMBRE_CATEGORIA;
			}
			set
			{
				if ((this._NOMBRE_CATEGORIA != value))
				{
					this._NOMBRE_CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCUENTO", DbType="Int NOT NULL")]
		public int DESCUENTO
		{
			get
			{
				return this._DESCUENTO;
			}
			set
			{
				if ((this._DESCUENTO != value))
				{
					this._DESCUENTO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PROVEEDORESResult
	{
		
		private int _idProveedor;
		
		private string _NOMBRE;
		
		private string _TELEFONO;
		
		public SP_OBTENER_PROVEEDORESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProveedor", DbType="Int NOT NULL")]
		public int idProveedor
		{
			get
			{
				return this._idProveedor;
			}
			set
			{
				if ((this._idProveedor != value))
				{
					this._idProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_IMAGENES_PRODUCTOResult
	{
		
		private int _idImagen;
		
		private int _idProducto;
		
		private System.Data.Linq.Binary _IMAGENURL;
		
		private string _IMAGEN_NOMBRE;
		
		public SP_OBTENER_IMAGENES_PRODUCTOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idImagen", DbType="Int NOT NULL")]
		public int idImagen
		{
			get
			{
				return this._idImagen;
			}
			set
			{
				if ((this._idImagen != value))
				{
					this._idImagen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int NOT NULL")]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this._idProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGENURL", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary IMAGENURL
		{
			get
			{
				return this._IMAGENURL;
			}
			set
			{
				if ((this._IMAGENURL != value))
				{
					this._IMAGENURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGEN_NOMBRE", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string IMAGEN_NOMBRE
		{
			get
			{
				return this._IMAGEN_NOMBRE;
			}
			set
			{
				if ((this._IMAGEN_NOMBRE != value))
				{
					this._IMAGEN_NOMBRE = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_CARRITOSResult
	{
		
		private int _idCarrito;
		
		private int _idCliente;
		
		private int _idProducto;
		
		private string _CODIGO;
		
		private string _NOMBRE;
		
		private int _CANTIDAD;
		
		public SP_OBTENER_CARRITOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarrito", DbType="Int NOT NULL")]
		public int idCarrito
		{
			get
			{
				return this._idCarrito;
			}
			set
			{
				if ((this._idCarrito != value))
				{
					this._idCarrito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", DbType="Int NOT NULL")]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					this._idCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int NOT NULL")]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this._idProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="NVarChar(9) NOT NULL", CanBeNull=false)]
		public string CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this._CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD", DbType="Int NOT NULL")]
		public int CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this._CANTIDAD = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PRODUCTOS_SEGUN_CATEGORIAResult
	{
		
		private int _idProducto;
		
		private string _CODIGO;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private int _STOCK;
		
		private decimal _PRECIO;
		
		private string _NOMBRE_PROVEEDOR;
		
		private string _NOMBRE_CATEGORIA;
		
		private int _DESCUENTO;
		
		public SP_OBTENER_PRODUCTOS_SEGUN_CATEGORIAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int NOT NULL")]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this._idProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="NVarChar(9) NOT NULL", CanBeNull=false)]
		public string CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this._CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCK", DbType="Int NOT NULL")]
		public int STOCK
		{
			get
			{
				return this._STOCK;
			}
			set
			{
				if ((this._STOCK != value))
				{
					this._STOCK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Decimal(10,0) NOT NULL")]
		public decimal PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PROVEEDOR", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NOMBRE_PROVEEDOR
		{
			get
			{
				return this._NOMBRE_PROVEEDOR;
			}
			set
			{
				if ((this._NOMBRE_PROVEEDOR != value))
				{
					this._NOMBRE_PROVEEDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_CATEGORIA", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NOMBRE_CATEGORIA
		{
			get
			{
				return this._NOMBRE_CATEGORIA;
			}
			set
			{
				if ((this._NOMBRE_CATEGORIA != value))
				{
					this._NOMBRE_CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCUENTO", DbType="Int NOT NULL")]
		public int DESCUENTO
		{
			get
			{
				return this._DESCUENTO;
			}
			set
			{
				if ((this._DESCUENTO != value))
				{
					this._DESCUENTO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PEDIDOS_CLIENTEResult
	{
		
		private int _idCliente;
		
		private string _CODIGO_PEDIDO;
		
		private int _ESTADO;
		
		private decimal _TOTAL;
		
		private string _DIRECCION;
		
		public SP_OBTENER_PEDIDOS_CLIENTEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", DbType="Int NOT NULL")]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					this._idCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_PEDIDO", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string CODIGO_PEDIDO
		{
			get
			{
				return this._CODIGO_PEDIDO;
			}
			set
			{
				if ((this._CODIGO_PEDIDO != value))
				{
					this._CODIGO_PEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Int NOT NULL")]
		public int ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Decimal(10,0) NOT NULL")]
		public decimal TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this._TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_DETALLE_PEDIDOS_CLIENTEResult
	{
		
		private int _idDetallePedido;
		
		private string _CODIGO_PEDIDO;
		
		private int _idProducto;
		
		private string _NOMBRE;
		
		private int _CANTIDAD;
		
		private decimal _PRECIO;
		
		public SP_OBTENER_DETALLE_PEDIDOS_CLIENTEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDetallePedido", DbType="Int NOT NULL")]
		public int idDetallePedido
		{
			get
			{
				return this._idDetallePedido;
			}
			set
			{
				if ((this._idDetallePedido != value))
				{
					this._idDetallePedido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_PEDIDO", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string CODIGO_PEDIDO
		{
			get
			{
				return this._CODIGO_PEDIDO;
			}
			set
			{
				if ((this._CODIGO_PEDIDO != value))
				{
					this._CODIGO_PEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int NOT NULL")]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this._idProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD", DbType="Int NOT NULL")]
		public int CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this._CANTIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Decimal(10,0) NOT NULL")]
		public decimal PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
